Better use drush 10
thunder/thunder-documentation pull request #11
Opened 2019-12-02 15:35 UTC by chrfritsch

2020-03-24 09:54 UTC, dbosen reviewed
drupal 10 is still broken

2020-07-14 06:53 UTC, chrfritsch commented
I think we can merge this

2020-07-14 06:59 UTC, dbosen requested changes

2020-07-14 06:59 UTC, dbosen commented on _includes/update23/requirements-media-update.md
> +composer require drush/drush:~10.0.0 --no-update
This will keep us on 10.0.*, better use  `composer require drush/drush:~10.0 --no-update`

2020-07-14 07:07 UTC, dbosen approved these changes

2020-07-14 07:08 UTC, merged