Thunder 6 update instructions
thunder/thunder-documentation pull request #14
Opened 2020-07-03 14:07 UTC by chrfritsch

2020-07-07 06:59 UTC, dbosen requested changes
We should add some instructions, how to test your custom codebase, if it is Drupl 9 compatible

2020-07-13 12:15 UTC, dbosen commented on _includes/update36/prerequisites.md
> +Before you start with the code and database update please disable the libraries module. The libraries module is not Drupal 9 compatible and
We should move this to the beginning, as the first step before composer update

2020-07-13 13:23 UTC, dbosen requested changes

2020-07-13 13:23 UTC, dbosen commented on _includes/update36/composer-adjustments.md
> +below mentioned modules please require them manually for your project.
Where is this list?

2020-07-13 13:24 UTC, chrfritsch commented on _includes/update36/composer-adjustments.md
> +below mentioned modules please require them manually for your project.
It's the entity module

2020-07-13 13:50 UTC, dbosen submitted a review, later dismissed

2020-07-14 06:07 UTC, chrfritsch commented
We should add https://github.com/caciobanu/behat-deprecation-extension for behat tests

2020-07-14 06:54 UTC, dbosen approved these changes

2020-07-14 06:55 UTC, merged